# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.firmware = [
    (pkgs.stdenvNoCC.mkDerivation (final: {
      name = "brcm-firmware";
      src = ./lib/firmware/brcm;
      installPhase = ''
        mkdir -p $out/lib/firmware/brcm
        cp ${final.src}/* "$out/lib/firmware/brcm"
      '';
    }))
  ]; 

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/867db499-d641-4eb5-a2b8-7d7a3479c10e";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/867db499-d641-4eb5-a2b8-7d7a3479c10e";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/867db499-d641-4eb5-a2b8-7d7a3479c10e";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/log" =
    { device = "/dev/disk/by-uuid/867db499-d641-4eb5-a2b8-7d7a3479c10e";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/526ee134-685c-4be9-8263-1a152d755eb7"; }
    ];

  environment.etc."systemd/system-sleep/rmmod.sh".source =
    pkgs.writeShellScript "rmmod.sh" ''
      if [ "$1" = "pre" ]; then
        ${pkgs.kmod}/bin/modprobe -r brcmfmac_wcc
        ${pkgs.kmod}/bin/modprobe -r brcmfmac
        ${pkgs.kmod}/bin/modprobe -r applesmc
      elif [ "$1" = "post" ]; then
        ${pkgs.kmod}/bin/modprobe brcmfmac
        ${pkgs.kmod}/bin/modprobe brcmfmac_wcc
      fi
    '';

  services.logind.extraConfig = ''
    HandlePowerKey=lock
    HandleLidSwitch=lock
    HandleLidSwitchExternalPower=lock
  '';

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
